Vagrant.configure(2) do |config|
  config.vm.box = "puphpet/ubuntu1404-x64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "private_network", ip: "192.168.133.7"
  config.vm.synced_folder "./", "/var/www"
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y mysql-server apache2 libapache2-mod-php5 php5-mysql php5-intl php5-mcrypt
  SHELL
end
